# Generated by Django 5.2.7 on 2025-12-14 15:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус корзини')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення корзини')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення корзини')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Покупець')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва категорії')),
                ('slug', models.SlugField(unique=True, verbose_name='Назва слагу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус категорії')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення категорії')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення категорії')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='online_store_app.category', verbose_name='Назва категорії')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='немає дій', verbose_name='Статус замовлення')),
                ('total_price', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1000000)], verbose_name='Сумма замовлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення замовлення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення замовлення')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупець')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Назва продукту')),
                ('description', models.TextField(max_length=500, verbose_name='Опис продукту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення продукту')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення продукту')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Кільксть продуктів на ринку')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус наявності продукту')),
                ('images', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Фотографії продукту')),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Середня оцінка рейтинга продукту')),
                ('rating_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість відгуків')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='online_store_app.category', verbose_name='Категірії продуктів')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000000)], verbose_name='Ціна продукту')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='Кількість продуктів у продавця')),
                ('discount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка на продукт')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Наявність продукту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення ціни на продукт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення ціни на продукт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_store_app.product', verbose_name='Вибранний продукт')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавець')),
            ],
            options={
                'unique_together': {('product', 'seller')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sellers',
            field=models.ManyToManyField(related_name='products', through='online_store_app.ProductSeller', to=settings.AUTH_USER_MODEL, verbose_name='Продавці які пропонують продукт'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='Кількість продуктів які були оплаченні')),
                ('price_at_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фіксована ціна в замовленні')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення оплаченного замовлення')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='online_store_app.order', verbose_name='Вміст замовлення')),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sellers', to='online_store_app.productseller', verbose_name='Пропозиція продавця продукту')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='Кількість продуктів в корзині')),
                ('price_at_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фіксована ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення корзини с продуктами')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='online_store_app.cart', verbose_name='Корзина')),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='online_store_app.productseller', verbose_name='Пропозиція продавця продукту')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг продукту')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Відгук')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальний відгук чи ні?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення відгуку')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення відгуку')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='online_store_app.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review_users', to=settings.AUTH_USER_MODEL, verbose_name='Покупець')),
            ],
            options={
                'unique_together': {('product', 'user')},
            },
        ),
    ]
