# Generated by Django 5.2.7 on 2025-12-20 18:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_at_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Фіксована ціна'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='online_store_app.category', verbose_name='Вибір основної категорії '),
        ),
        migrations.AlterField(
            model_name='productseller',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sellers', to='online_store_app.product', verbose_name='Вибранний продукт'),
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг продавця')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Відгук')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальний відгук чи ні?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення відгуку')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення відгуку')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Продавець')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_review_users', to=settings.AUTH_USER_MODEL, verbose_name='Покупець')),
            ],
            options={
                'unique_together': {('seller', 'user')},
            },
        ),
    ]
