# Generated by Django 5.2.7 on 2026-01-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store_app', '0002_alter_cartitem_price_at_time_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productseller',
            name='final_price',
            field=models.IntegerField(default=0, verbose_name='Фінальна ціна продукту'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Фотографії продукту'),
        ),
    ]
