# Generated by Django 5.2.7 on 2025-10-16 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='direction',
            field=models.CharField(default=5, max_length=70),
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_members',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
