# Generated by Django 5.2.7 on 2025-10-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_course_description_course_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.CharField(default='None', max_length=70),
        ),
    ]
