# Generated by Django 5.2.7 on 2025-10-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_remove_course_number_of_members_course_limit_members_and_more'),
        ('members_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='list_of_members',
        ),
        migrations.AddField(
            model_name='course',
            name='list_of_members',
            field=models.ManyToManyField(blank=True, related_name='courses', to='members_app.member'),
        ),
    ]
