# Generated by Django 5.2.7 on 2025-10-22 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0005_remove_course_list_of_members_course_list_of_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='course',
            name='limit_members',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
