# Generated by Django 5.2.7 on 2025-11-13 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_alter_course_direction_alter_course_limit_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(22), django.core.validators.MaxValueValidator(55)])),
                ('gender', models.CharField(choices=[('', 'Будь ласка виберіть стать:'), ('M', 'Чоловіча'), ('W', 'Жіноча')], max_length=1)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='courses_app.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='courses_app.teacher'),
        ),
    ]
