# Generated by Django 5.2.7 on 2025-11-16 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0008_alter_teacher_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='courses_app.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses_app.course'),
        ),
    ]
