# Generated by Django 5.2.7 on 2025-11-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0009_alter_course_teacher_alter_teacher_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
