# Generated by Django 5.2.7 on 2025-11-20 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def set_default_user(apps, schema_editor):
    user = apps.get_model('accounts', 'CourseUser')
    course_model = apps.get_model('courses_app', 'Course')
    teacher_model = apps.get_model('courses_app', 'Teacher')
    default_user = user.objects.get(id=1)
    course_model.objects.filter(creator__isnull=True).update(creator=default_user)
    teacher_model.objects.filter(creator__isnull=True).update(creator=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0012_alter_course_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_default_user),
    ]
