# Generated by Django 5.2.7 on 2025-10-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
