# Generated by Django 5.2.7 on 2025-11-07 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_courseuser_phone_number_alter_courseuser_password'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_log', models.CharField(max_length=35)),
                ('action_type', models.CharField(default='Немає дій')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.PositiveIntegerField()),
                ('target_id', models.PositiveIntegerField()),
                ('relation_type', models.CharField(max_length=90)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('model_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='contenttypes.contenttype')),
                ('target_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='contenttypes.contenttype')),
            ],
        ),
    ]
