# Generated by Django 5.2.7 on 2025-11-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_billingadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='name_object',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
