# Generated by Django 5.2.7 on 2025-12-10 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=30, verbose_name='Назва ролі')),
                ('description', models.TextField(max_length=500, verbose_name='Опис ролі')),
                ('description_permissions', models.TextField(max_length=500, verbose_name='Опис можливостей ролі')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Ролі',
            },
        ),
        migrations.CreateModel(
            name='OnlineStoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(unique=True, verbose_name='Електронна адреса')),
                ('phone_number', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Номер телефону')),
                ('first_name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=45, verbose_name='Прізвище')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регестрації')),
                ('last_date_login', models.DateTimeField(blank=True, null=True, verbose_name='Дата останнього логіну')),
                ('preffered_language', models.CharField(choices=[('uk', 'Ukrainian'), ('us', 'English')], default='uk', max_length=10, verbose_name='Мова')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='accountss.roles', verbose_name='Ролі користувача')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
    ]
