# Generated by Django 5.2.7 on 2025-12-10 18:03

from django.db import migrations

def create_default_roles(apps, schema_editor):
    role_models = apps.get_model('accountss', 'Roles')
    if not role_models.objects.filter(name_role='admin').exists():
        create_role_admin = role_models.objects.create(
            name_role = 'admin',
            description = 'Опис ролі: розблоковані всі можливості',
            description_permissions = 'Опис можливостей ролі: повна свобода дій',
        )
    if not role_models.objects.filter(name_role='buyer').exists():
        create_role_buyer = role_models.objects.create(
            name_role = 'buyer',
            description = (
                'Опис ролі: '
                'людина яка здійснює замовлення, '
                'купує необхідні товари та планує наступні покупки'
            ),
            description_permissions = (
                'Опис можливостей ролі: '
                'можливість переглядати шаблони товарів, '
                'можливість офорлювати замовлення '
                'та спілкуватися с продавцем'
            ),
        )
    if not role_models.objects.filter(name_role='seller').exists():
        create_role_seller = role_models.objects.create(
            name_role = 'seller',
            description = (
                'Опис ролі: ' 
                'Людина яка виставляє та пропонує свої товари для продажу'
            ),
            description_permissions = (
                'Опис можливостей ролі: '
                'можливість створювати шаблон товару, '
                'можливість редагувати шаблон товару, '
                'можливість видаляти шаблон товару, '
                'передивлятись свої шаблони товарів та інших в глобальному доступі'
            )
        )

class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles)
    ]
