# Generated by Django 5.2.7 on 2025-12-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0002_create_default_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestoreuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='onlinestoreuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=45, verbose_name='Прізвище'),
        ),
    ]
