# Generated by Django 5.2.7 on 2025-12-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0003_alter_onlinestoreuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinestoreuser',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг продавця'),
        ),
        migrations.AddField(
            model_name='onlinestoreuser',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість відгуків продавця'),
        ),
    ]
