# Generated by Django 5.2.7 on 2026-01-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0004_onlinestoreuser_rating_onlinestoreuser_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestoreuser',
            name='roles',
            field=models.ManyToManyField(blank=True, default='buyer', related_name='users', to='accountss.roles', verbose_name='Ролі користувача'),
        ),
    ]
