# Generated by Django 5.2.7 on 2025-10-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0005_remove_course_list_of_members_course_list_of_members'),
        ('members_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses_app.course'),
        ),
    ]
