# Generated by Django 5.2.7 on 2025-10-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0003_alter_member_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='course',
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Чоловіча'), ('W', 'Жіноча')], default='None'),
        ),
    ]
