# Generated by Django 5.2.7 on 2025-10-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0004_remove_member_course_alter_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('', 'Будь ласка виберіть стать:'), ('M', 'Чоловіча'), ('W', 'Жіноча')], max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
