# Generated by Django 5.2.7 on 2025-10-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0005_alter_member_gender_alter_member_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Чоловіча'), ('W', 'Жіноча')], max_length=1),
        ),
    ]
