# Generated by Django 5.2.7 on 2025-10-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0006_alter_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('', 'Будь ласка виберіть стать:'), ('M', 'Чоловіча'), ('W', 'Жіноча')], max_length=1),
        ),
    ]
