# Generated by Django 5.2.7 on 2025-11-20 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def set_default_user(apps, schema_editor):
    user = apps.get_model('accounts', 'CourseUser')
    member_model = apps.get_model('members_app', 'Member')
    default_user = user.objects.get(id=1)
    member_model.objects.filter(creator__isnull=True).update(creator=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0007_alter_member_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_default_user),
    ]
